# Site settings
theme: minima
title: opsMason
description: > # this means to ignore newlines until "baseurl:"
  It's just me, at a keyboard. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://opsmason.com" # the base hostname & protocol for your site
twitter_username: opsmason
github_username:  opsmason

timezone: America/New_York
paginate: 1

plugins:
  - jekyll-feed
  
# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
minima:
  date_format: "%Y-%m-%d"
show_excerpts: true
