# Site settings
google_analytics: G-YREENXZ34R
theme: minima
title: opsMason
description: It's just me, at a keyboard.
baseurl: ""
url: "https://www.opsmason.com" # the base hostname & protocol for your site
github_username:  opsmason
show_excerpts: true
timezone: America/New_York

plugins:
  - jekyll-feed
  
# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
minima:
  date_format: "%Y-%m-%d"
  skin: "solarized"

tag_desc:
  podcasts: Why do I keep typing 'podcats'?
  self: Navel Gazing
  tech: beep boop
  x-wing: Pew Pew!
